import { TokenPlan } from '../types';

export const BANK_DETAILS = {
  accountNumber: 'MN510050099106696285',
  bankName: 'Хаан Банк / Голомт Банк (MN IBAN)',
  accountName: 'Gemini Mind (P. Websiter)',
  iban: 'MN510050099106696285',
  discordWebhookUrl: 'https://discord.com/api/webhooks/1554542116452044811/PPlVyn6hovwjBoz1-36pAyGKjHPa-hNOBisnx8-RZIo1GTmbxGlGX1mIrMbFC0I97VkL',
};

export const TOKEN_PLANS: TokenPlan[] = [
  {
    id: 'free',
    name: 'Free Starter',
    nameMn: 'Үнэгүй Эхлэл',
    tokens: 25000,
    priceMNT: 0,
    priceFormatted: '0 ₮',
    period: 'Сар бүр',
    badge: 'Үнэгүй',
    description: 'Ерөнхий хичээлийн асуулт ба үндсэн бодлого бодоход тохиромжтой.',
    features: [
      '25,000 токен / сар (~50 бодлого)',
      'Бүх хичээлийн туслах (Монгол хэл, Түүх, Англи)',
      'Үндсэн Google Search хайлт',
      'Стандарт хурдны Gemini 3.8 Flash',
    ],
  },
  {
    id: 'pro',
    name: 'Scholar Standard',
    nameMn: 'Сурагч Standard',
    tokens: 250000,
    priceMNT: 25000,
    priceFormatted: '25,000 ₮',
    period: 'Сар бүр',
    badge: 'Эрэлттэй',
    popular: true,
    description: 'Математик, физик, химийн бодлогуудыг алхамчлан бүрэн бодох үндсэн багц.',
    features: [
      '250,000 токен / сар (~500 бодлого)',
      'Зураг уншиж бодох (Vision Solver) бүрэн дэмжлэг',
      'Математикийн нарийвчилсан алхамчилсан баталгаа',
      'Google Search шууд эх сурвалж холбоос',
      'Дуут уншигч & дуут оруулалт',
      'Шалгалтын бэлтгэл тест автоматаар зохиох',
    ],
  },
  {
    id: 'master',
    name: 'Scholar Pro Plus',
    nameMn: 'Ахлах Pro Plus',
    tokens: 650000,
    priceMNT: 49000,
    priceFormatted: '49,000 ₮',
    period: 'Сар бүр',
    badge: 'Гүнзгийрүүлсэн',
    description: 'Их дээд сургууль, ЭЕШ-д бэлтгэх, нарийн тооцоолол хийх хүчирхэг багц.',
    features: [
      '650,000 токен / сар (~1,300 бодлого)',
      'Олимпиад & ЭЕШ-ийн гүнзгийрүүлсэн математик',
      'AI Builder & Интерактив амьд кодын Sandbox',
      'Deep Research баримт нягтлах горим',
      'Тэргүүн зэргийн серверийн тэргүүлэх эгнээ',
    ],
  },
  {
    id: 'owner',
    name: 'Ultra Master Olympiad',
    nameMn: 'Элсэлт & Мастер',
    tokens: 1500000,
    priceMNT: 89000,
    priceFormatted: '89,000 ₮',
    period: 'Сар бүр',
    badge: 'Мастер',
    description: 'Бүх боломж нээлттэй, хамгийн өндөр токентой дээд зэрэглэлийн багц.',
    features: [
      '1,500,000 токен / сар (~3,000 бодлого)',
      'Хязгааргүй амьд код ба симуляци туршилт',
      'Бүх төрлийн шинжлэх ухааны томьёоны задлан шинжилгээ',
      'VIP тэргүүн ээлжийн сервер хурд',
      'Хувийн зөвлөх туслах горим',
    ],
  },
];
